<a href="https://colab.research.google.com/github/kushagra1102/object-detection/blob/main/color_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
!pip install pillow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import requests
from PIL import Image
import shutil
import urllib

In [10]:
import urllib.request

('images/my_image.jpg', <http.client.HTTPMessage at 0x7f2a7c16f3d0>)

In [11]:
import pandas as pd
labels_csv = pd.read_csv("/content/updated_dataset.csv")
print(labels_csv.describe())
print(labels_csv.head())

       dominant_color                                             images  \
count            1284                                               1393   
unique             34                                               1310   
top              Blue  http://assets.myntassets.com/v1/assets/images/...   
freq              182                                                  3   

                          Unnamed: 2  
count                             23  
unique                             5  
top     https://www.myntra.com/libas  
freq                              14  
  dominant_color                                             images Unnamed: 2
0          Black  http://assets.myntassets.com/v1/assets/images/...        NaN
1          Black  http://assets.myntassets.com/v1/assets/images/...        NaN
2          White  http://assets.myntassets.com/v1/assets/images/...        NaN
3           Pink  http://assets.myntassets.com/v1/assets/images/...        NaN
4         Yellow  http://asse

In [14]:
labels_csv.drop(['Unnamed: 2'],axis = 1,inplace=True)

In [15]:
labels_csv.dropna(inplace=True)

In [16]:
labels_csv['images'] = labels_csv['images'].str.strip()

In [17]:
labels_csv['images'] = labels_csv['images'].str.split("|")

In [19]:
labels_csv.head()

dominant_color                                             images
0          Black  [http://assets.myntassets.com/v1/assets/images...
1          Black  [http://assets.myntassets.com/v1/assets/images...
2          White  [http://assets.myntassets.com/v1/assets/images...
3           Pink  [http://assets.myntassets.com/v1/assets/images...
4         Yellow  [http://assets.myntassets.com/v1/assets/images...

In [36]:
for i, j in labels_csv.iterrows():
    image_url = j.images[0] 
    save_name = 'images3/' + str(i) + '.jpg'
    urllib.request.urlretrieve(image_url, save_name)

In [37]:
!zip -r /content/images.zip /content/images3

  adding: content/images3/ (stored 0%)
  adding: content/images3/442.jpg (deflated 0%)
  adding: content/images3/1140.jpg (deflated 0%)
  adding: content/images3/226.jpg (deflated 0%)
  adding: content/images3/1255.jpg (deflated 1%)
  adding: content/images3/1273.jpg (deflated 4%)
  adding: content/images3/196.jpg (deflated 1%)
  adding: content/images3/780.jpg (deflated 0%)
  adding: content/images3/420.jpg (deflated 0%)
  adding: content/images3/887.jpg (deflated 1%)
  adding: content/images3/1380.jpg (deflated 1%)
  adding: content/images3/349.jpg (deflated 1%)
  adding: content/images3/942.jpg (deflated 1%)
  adding: content/images3/881.jpg (deflated 5%)
  adding: content/images3/1272.jpg (deflated 1%)
  adding: content/images3/542.jpg (deflated 1%)
  adding: content/images3/590.jpg (deflated 1%)
  adding: content/images3/879.jpg (deflated 1%)
  adding: content/images3/1200.jpg (deflated 2%)
  adding: content/images3/717.jpg (deflated 5%)
  adding: content/images3/873.jpg (deflated

In [41]:
from google.colab import files
files.download('/content/images.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [39]:
labels_csv.describe()

dominant_color                                             images
count            1284                                               1284
unique             34                                               1210
top              Blue  [http://assets.myntassets.com/v1/assets/images...
freq              182                                                  3

In [40]:
from tensorflow.keras.layers import Input, Lambda, Dense, Flatten,Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.vgg19 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd
import os
import cv2
import matplotlib.pyplot as plt

In [43]:
train_path="/content/images3"

In [49]:
labels_csv

dominant_color                                             images
0             Black  [http://assets.myntassets.com/v1/assets/images...
1             Black  [http://assets.myntassets.com/v1/assets/images...
2             White  [http://assets.myntassets.com/v1/assets/images...
3              Pink  [http://assets.myntassets.com/v1/assets/images...
4            Yellow  [http://assets.myntassets.com/v1/assets/images...
...             ...                                                ...
1388           Navy  [http://assets.myntassets.com/v1/assets/images...
1389           Pink  [http://assets.myntassets.com/v1/assets/images...
1390          Beige  [http://assets.myntassets.com/v1/assets/images...
1391           Pink  [http://assets.myntassets.com/v1/assets/images...
1392          Black  [http://assets.myntassets.com/v1/assets/images...

[1284 rows x 2 columns]

In [71]:
filenames = ["/content/images3/" + str(fname) + ".jpg" for fname in labels_csv.index]

In [72]:
filenames[:25]

['/content/images3/0.jpg',
 '/content/images3/1.jpg',
 '/content/images3/2.jpg',
 '/content/images3/3.jpg',
 '/content/images3/4.jpg',
 '/content/images3/5.jpg',
 '/content/images3/6.jpg',
 '/content/images3/7.jpg',
 '/content/images3/8.jpg',
 '/content/images3/9.jpg',
 '/content/images3/10.jpg',
 '/content/images3/11.jpg',
 '/content/images3/12.jpg',
 '/content/images3/13.jpg',
 '/content/images3/14.jpg',
 '/content/images3/15.jpg',
 '/content/images3/16.jpg',
 '/content/images3/17.jpg',
 '/content/images3/18.jpg',
 '/content/images3/19.jpg',
 '/content/images3/21.jpg',
 '/content/images3/22.jpg',
 '/content/images3/23.jpg',
 '/content/images3/26.jpg',
 '/content/images3/27.jpg']

In [73]:
if len(os.listdir("/content/images3/")) == len(filenames):
  print("Filenames match actual amount of files!")
else:
  print("Filenames do not match actual amount of files, check the target directory.")

Filenames match actual amount of files!


In [74]:
len(filenames)

1284

In [75]:
filenames[1000]

'/content/images3/1073.jpg'

In [80]:
import tensorflow as tf
import tensorflow_hub as hub

In [81]:
import numpy as np
labels = labels_csv["dominant_color"].to_numpy() # convert labels column to NumPy array
labels[:10]

array(['Black', 'Black', 'White', 'Pink', 'Yellow', 'Beige', 'Green',
       'Blue', 'Maroon', 'Orange'], dtype=object)

In [82]:
if len(labels) == len(filenames):
  print("Number of labels matches number of filenames!")
else:
  print("Number of labels does not match number of filenames, check data directories.")

Number of labels matches number of filenames!


In [83]:
unique_breeds = np.unique(labels)
len(unique_breeds)

34

In [84]:
print(labels[0])
labels[0] == unique_breeds

Black


array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [85]:
boolean_labels = [label == np.array(unique_breeds) for label in labels]
boolean_labels[:2]

[array([False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False]),
 array([False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False])]

In [86]:
print(labels[0]) # original label
print(np.where(unique_breeds == labels[0])[0][0]) # index where label occurs
print(boolean_labels[0].argmax()) # index where label occurs in boolean array
print(boolean_labels[0].astype(int)) # there will be a 1 where the sample label occurs


Black
1
1
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [87]:
X = filenames
y = boolean_labels

In [88]:
IMG_SIZE = 224

def process_image(image_path):
  """
  Takes an image file path and turns it into a Tensor.
  """
  # Read in image file
  image = tf.io.read_file(image_path)
  # Turn the jpeg image into numerical Tensor with 3 colour channels (Red, Green, Blue)
  image = tf.image.decode_jpeg(image, channels=3)
  # Convert the colour channel values from 0-225 values to 0-1 values
  image = tf.image.convert_image_dtype(image, tf.float32)
  # Resize the image to our desired size (224, 244)
  image = tf.image.resize(image, size=[IMG_SIZE, IMG_SIZE])
  return image

In [89]:
def get_image_label(image_path, label):
  """
  Takes an image file path name and the associated label,
  processes the image and returns a tuple of (image, label).
  """
  image = process_image(image_path)
  return image, label